#!/bin/bash

# This script counts down from a specified number.

read -p "Enter a number to countdown from: " count

while [ $count -ge 0 ]; do
    echo $count
    ((count--))  # Decrement the count
done

echo "Blast off!"
